#!/usr/bin/env bash
set -e

HELP="\
DOTFILE SETUP
=============
sonro <sonro@gmx.com>

Setup software and configurations for development on *nix

USAGE: setup [OPTIONS]

OPTIONS:
	-h, --help       Prints help information
	-s, --server     Setup without node and neovim (for a more minimal install)
	-n, --new        Replace existing config files

If any combination of these flags are set: only those functions will run
	-f, --files      Setup files
	-i, --install    Install software
	-p, --plugins	 Install plugins
"

# Config
DOTFILE_DIR="$HOME/.dotfiles"

# Options
FRESH=false
SERVER=false
EXPLICIT=false
FILES=false
INSTALL=false
PLUGINS=false

main() {
	parse_args "$@"

	if [[ "$EXPLICIT" == false || "$FILES" == true ]]; then
		source "$DOTFILE_DIR/setup-src/setupfiles.bash"
		setup_files "$SERVER" "$DOTFILE_DIR" "$FRESH"
	fi

	if [[ "$EXPLICIT" == false || "$INSTALL" == true ]]; then
		source "$DOTFILE_DIR/setup-src/installsoftware.bash"
		install_software "$SERVER" "$DOTFILE_DIR"
	fi

	if [[ "$EXPLICIT" == false || "$PLUGINS" == true ]]; then
		source "$DOTFILE_DIR/setup-src/installplugins.bash"
		install_plugins "$SERVER" "$DOTFILE_DIR" "$FRESH"
	fi

	return 0
}

parse_args() {
	for opt in "$@"; do
		case "$opt" in
			-n|--new) FRESH=true;;
			-s|--server) SERVER=true;;
			-h|--help)
				echo "$HELP"
				exit 0
				;;
			-f|--files) 
				EXPLICIT=true
				FILES=true
				;;
			-i|--install) 
				EXPLICIT=true
				INSTALL=true
				;;
			-p|--plugins) 
				EXPLICIT=true
				PLUGINS=true
				;;
		esac
	done

	return 0
}

main "$@"
